Easy Billing/Easy Billing/Models/Products_For_Sale.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBilling.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Products_For_Sale
    {
        [Display(Name = "Token")]
        public string Token_Number { get; set; }
        [Display(Name = "Company Token")]
        public string Product_Token { get; set; }
        [Display(Name = "Company name")]
        public string Product_name { get; set; }
        public int Pieces { get; set; }
        [Display(Name = "Amount including tax")]
        public decimal Amout_after_tax { get; set; }
        public decimal Total { get; set; }
        [Display(Name = "Tyre size")]
        public string Tyre_Size { get; set; }
        [Display(Name = "Supplier token")]
        public string Supplier_token { get; set; }
        [Display(Name = "Supplier name")]
        public string Supplier_name { get; set; }
        public System.DateTime Date { get; set; }
        [Display(Name = "Purchase price")]
        public decimal Purchase_Price { get; set; }
        public decimal CGST { get; set; }
        public decimal SGST { get; set; }
        [Display(Name = "Administrator Token number")]
        public string Administrator_Token_number { get; set; }
        [Display(Name = "Administrator name")]
        public string Administrator_name { get; set; }
        [Display(Name = "Approve date")]
        public System.DateTime Approve_date { get; set; }
        public bool Approve { get; set; }
        [Display(Name = "Selling price")]
        public decimal Selling_Price { get; set; }
        public int StockIn { get; set; }
        public decimal Up_Selling_Price { get; set; }
        public decimal Up_CGST { get; set; }
        public decimal Up_SGST { get; set; }
        [Display(Name = "Delivery contact number")]
        public long Delivery_contact_number { get; set; }
        [Display(Name = "Delivery address")]
        public string Delivery_address { get; set; }
        [Display(Name = "Item Id")]
        public string Item_tyre_Id { get; set; }
        [Display(Name = "Invoice number")]
        public string Purchase_number { get; set; }
        [Display(Name ="Invoice date")]
        public System.DateTime PurchaseDate { get; set; }
        [Display(Name = "Tyre make")]
        public string Tyre_make { get; set; }
        [Display(Name = "Tyre type")]
        public string Tyre_type { get; set; }
        [Display(Name = "Tyre feel")]
        public string Tyre_feel { get; set; }
        public virtual Product Product { get; set; }
    }
}

Easy Billing/Easy Billing/Controllers/ProductsForSaleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;
using EasyBilling.Models;
using System.IO;
using System.Drawing;
using System.Drawing.Imaging;
using System.Net.Http;
using PagedList;
using System.Web;
using System.Data.Entity.Validation;

namespace EasyBilling.Controllers
{
    public class ProductsForSaleController : MybaseController
    {
       
        private EasyBillingEntities db = new EasyBillingEntities();

        // GET: ProductsForSale
        public async Task<ActionResult> Index(int? page, string keyword)
        {
            var products_For_Sales = db.Products_For_Sales.Include(p => p.Product).Distinct();
            //return View(await products_For_Sales.ToListAsync());
            var dcmlempty = decimal.Parse("0.000");
            //var products_For_Sales = (from pdfs in db.Products_For_Sales
            //                          join stk in db.Stocks on pdfs.Token_Number equals stk.Product_Token
            //                          where (stk.Pieces != 0 ) && pdfs.Approve == true

            //                          select pdfs).Distinct();

            ViewBag.productstks = await (from pdfs in db.Products_For_Sales
                                         join stk in db.Stocks on pdfs.Token_Number equals stk.Product_Token
                                         //where pdfs.Approve == true

                                         select stk).Distinct().ToListAsync();
            ViewBag.billno = null;
            var results = (from p in db.Products_For_Sales
                       
                          group p.Tyre_Size by p.Tyre_Size into g
                         
                          select new CategoryClass { Product_name = g.Key, Subcategory = g.Distinct().ToList() }).ToList();
            ViewBag.ctgry = results;
            if (!string.IsNullOrEmpty(keyword))
            {
                return View(products_For_Sales.Where(f => f.Product_name.Contains(keyword)).OrderByDescending(z=>z.Date).Distinct().ToList().ToPagedList(page ?? 1, 9));
            }
            return View(products_For_Sales.OrderByDescending(z => z.Date).Distinct().ToList().ToPagedList(page ?? 1, 9));
        }
        public JsonResult GetStudents(string term)
        {
         //   var dcmlempty = decimal.Parse("0.000");
            List<string> _Products_For_Sales = (from pdfs in db.Products_For_Sales
                                     join stk in db.Stocks on pdfs.Token_Number equals stk.Product_Token
                                      where (stk.Pieces != 0) /*&& pdfs.Approve == true*/
                                      && pdfs.Product_name.Contains(term)
                                      select pdfs.Product_name).Distinct().ToList();
            if (_Products_For_Sales.Count == 0)
            {
                _Products_For_Sales.Add("No tyre is matched with this name...");
            }
            return Json(_Products_For_Sales, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Getsubcat(string term)
        {
            List<string> _Products_For_Sales = (from p in db.Products_For_Sales
                          where p.Tyre_Size.Contains(term)
                                                select p.Tyre_Size).Distinct().ToList();
           
            if (_Products_For_Sales.Count == 0)
            {
                _Products_For_Sales.Add("No subcategory found. You can can create new one...");
            }
            return Json(_Products_For_Sales, JsonRequestBehavior.AllowGet);
        }

        public PartialViewResult Search(string keyword)
        {
            var dcmlempty = decimal.Parse("0.000");
            if (!string.IsNullOrEmpty(keyword))
            {
                
                var products = (from pdfs in db.Products_For_Sales
                              join stk in db.Stocks on pdfs.Token_Number equals stk.Product_Token
                              orderby pdfs.Date descending
                              where (stk.Pieces != 0) && pdfs.Approve == true
                              && pdfs.Product_name.Contains(keyword) 
                              select pdfs).Distinct().ToList();
                
                return PartialView("_Products", products);
            }else
            {
                
                var prdall = (from pdfs in db.Products_For_Sales
                                                    join stk in db.Stocks on pdfs.Token_Number equals stk.Product_Token
                              orderby pdfs.Date descending
                              where (stk.Pieces != 0 ) && pdfs.Approve == true
                                                   
                                                    select pdfs).Distinct().ToList();

                return PartialView("_Products", prdall);
            }
           
        }

        public PartialViewResult Filter(string key, int? page,string keysub)
        {
            var dcmlempty = decimal.Parse("0.000");
            if (!string.IsNullOrEmpty(key))
            {
                if (!string.IsNullOrEmpty(keysub))
                {
                    var products = (from pdfs in db.Products_For_Sales
                                    join stk in db.Stocks on pdfs.Token_Number equals stk.Product_Token
                                    orderby pdfs.Date descending
                                    where pdfs.Approve == true
                                    && pdfs.Product_name == key && pdfs.Tyre_Size==keysub
                                    select pdfs).Distinct().ToList().ToPagedList(page ?? 1, 9);
                    return PartialView("_CategoryProducts", products);
                }
                else
                {

                    var products = (from pdfs in db.Products_For_Sales
                                    join stk in db.Stocks on pdfs.Token_Number equals stk.Product_Token
                                    orderby pdfs.Date descending
                                    where pdfs.Approve == true
                                    && pdfs.Product_name == key
                                    select pdfs).Distinct().ToList().ToPagedList(page ?? 1, 9);
                    return PartialView("_CategoryProducts", products);
                }
                
            }
            else
            {

                var prdall = (from pdfs in db.Products_For_Sales
                              join stk in db.Stocks on pdfs.Token_Number equals stk.Product_Token
                              orderby pdfs.Date descending
                              where pdfs.Approve == true

                              select pdfs).Distinct().ToList().ToPagedList(page ?? 1, 9);

                return PartialView("_CategoryProducts", prdall);
            }

        }
        public PartialViewResult FilterForBilling(string key, int? page, string keysub)
        {
            var dcmlempty = decimal.Parse("0.000");
            if (!string.IsNullOrEmpty(key))
            {
                if (!string.IsNullOrEmpty(keysub))
                {
                    var products = (from pdfs in db.Products_For_Sales
                                    join stk in db.Stocks on pdfs.Token_Number equals stk.Product_Token
                                    orderby pdfs.Date descending
                                    where pdfs.Approve == true
                                    && pdfs.Product_name == key && pdfs.Tyre_Size == keysub
                                    select pdfs).Distinct().ToList().ToPagedList(page ?? 1, 9);
                    return PartialView("_BillingCategoryProducts", products);
                }
                else
                {

                    var products = (from pdfs in db.Products_For_Sales
                                    join stk in db.Stocks on pdfs.Token_Number equals stk.Product_Token
                                    orderby pdfs.Date descending
                                    where pdfs.Approve == true
                                    && pdfs.Product_name == key
                                    select pdfs).Distinct().ToList().ToPagedList(page ?? 1, 9);
                    return PartialView("_BillingCategoryProducts", products);
                }

            }
            else
            {

                var prdall = (from pdfs in db.Products_For_Sales
                              join stk in db.Stocks on pdfs.Token_Number equals stk.Product_Token
                              orderby pdfs.Date descending
                              where pdfs.Approve == true

                              select pdfs).Distinct().ToList().ToPagedList(page ?? 1, 9);

                return PartialView("_BillingCategoryProducts", prdall);
            }

        }
        //[Authorize]

        public async Task<ActionResult> Billing(int? page, string keyword)
        {
            var dcmlempty = decimal.Parse("0.000");
            var products_For_Sales = (from pdfs in db.Products_For_Sales
                           join stk in db.Stocks on pdfs.Token_Number equals stk.Product_Token
                                     
                                      where (stk.Pieces != 0 ) && pdfs.Approve == true

                            select pdfs).Distinct();
            ViewBag.productstks = await (from pdfs in db.Products_For_Sales
                                         join stk in db.Stocks on pdfs.Token_Number equals stk.Product_Token
                                         orderby pdfs.Date descending
                                         where (stk.Pieces != 0 ) && pdfs.Approve == true

                                         select stk).Distinct().ToListAsync();
            ViewBag.billno = null;
            var results = (from p in db.Products_For_Sales

Easy Billing/Easy Billing/Controllers/Webapi/ProductsForSaleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace EasyBilling.Controllers.Webapi
{
    public class ProductsForSaleController : ApiController
    {
    }
}

Easy Billing/Easy Billing/Views/ProductsForSale/Create.cshtml
@model EasyBilling.Models.Products_For_Sale

@{
    ViewBag.Title = "Product creation";

}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">

<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>


<div class="container" style="padding-bottom:10px">
    <h1 class=" <form ititle-agile text-center">Stock Entry...</h1>
    @*<form class="form-inline" action="/action_page.php">*@
    <div id="mainrow" class="col-md-12 col-lg-12 col-sm-12">
        @using (Html.BeginForm("Create", "ProductsForSale", FormMethod.Post, new { @class = "form-inline" }))
        {
        <div style="padding:3px 3px 3px 3px" class="col-md-12 col-lg-12 col-sm-12">
            <div class="form-group col-md-3 col-lg-3 col-sm-3">
                @Html.LabelFor(model => model.Purchase_number)
                @Html.EditorFor(model => model.Purchase_number, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", @Value = ViewBag.lstid } })
              
                @Html.ValidationMessageFor(model => model.Purchase_number, "", new { @class = "text-danger" })

            </div>

            <div class="form-group col-md-3 col-lg-3 col-sm-3">
                @Html.LabelFor(model => model.PurchaseDate)
                @Html.EditorFor(model => model.PurchaseDate, new { htmlAttributes = new { @class = "form-control pp", @type = "date" } })

                @Html.ValidationMessageFor(model => model.PurchaseDate, "", new { @class = "text-danger" })

            </div>
            <div class="form-group col-md-3 col-lg-3 col-sm-3">
                @Html.LabelFor(model => model.Delivery_contact_number)
                @Html.EditorFor(model => model.Delivery_contact_number, new { htmlAttributes = new { @class = "form-control pp", @type = "number" } })

                @Html.ValidationMessageFor(model => model.Delivery_contact_number, "", new { @class = "text-danger" })

            </div>
            <div class="form-group col-md-3 col-lg-3 col-sm-3">
                @Html.LabelFor(model => model.Delivery_address)
                @Html.EditorFor(model => model.Delivery_address, new { htmlAttributes = new { @class = "form-control pp" } })

                @Html.ValidationMessageFor(model => model.Delivery_address, "", new { @class = "text-danger" })

            </div>

        </div>
        <div style="padding:3px 3px 3px 3px" class="col-md-12 col-lg-12 col-sm-12">
            <div class="form-group col-md-3 col-lg-3 col-sm-3">
                @Html.LabelFor(model => model.Item_tyre_Id)
                @Html.DropDownListFor(model => model.Item_tyre_Id, new SelectList(@ViewBag.itmtyres, "Token_number", "Item_Id"),
                                                "Select Item Id", new { @class = "form-control nm" })
                @Html.ValidationMessageFor(model => model.Product_name, "", new { @class = "text-danger" })

            </div>

            <div class="form-group col-md-3 col-lg-3 col-sm-3">
                @Html.LabelFor(model => model.Tyre_make)
                @Html.EditorFor(model => model.Tyre_make, new { htmlAttributes = new { @class = "form-control pp" } })

                @Html.ValidationMessageFor(model => model.Tyre_make, "", new { @class = "text-danger" })

            </div>
            <div class="form-group col-md-3 col-lg-3 col-sm-3">
                @Html.LabelFor(model => model.Tyre_type)
                @Html.EditorFor(model => model.Tyre_type, new { htmlAttributes = new { @class = "form-control pp" } })

                @Html.ValidationMessageFor(model => model.Tyre_type, "", new { @class = "text-danger" })

            </div>
            <div class="form-group col-md-3 col-lg-3 col-sm-3">
                @Html.LabelFor(model => model.Tyre_feel)
                @Html.EditorFor(model => model.Tyre_feel, new { htmlAttributes = new { @class = "form-control pp" } })

                @Html.ValidationMessageFor(model => model.Tyre_feel, "", new { @class = "text-danger" })

            </div>

        </div>
            <div style="padding:3px 3px 3px 3px" class="col-md-12 col-lg-12 col-sm-12">
                <div class="form-group col-md-4 col-lg-4 col-sm-4">
                    @Html.LabelFor(model => model.Product_name)
                    @Html.DropDownListFor(model => model.Product_name, new SelectList(@ViewBag.prdct, "Token_Number", "Product_name"),
                                                    "Select Product name", new { @class = "form-control nm" })
                    @Html.ValidationMessageFor(model => model.Product_name, "", new { @class = "text-danger" })

                </div>

                <div class="form-group col-md-3 col-lg-3 col-sm-3">
                    @Html.LabelFor(model => model.Tyre_Size)
                    @Html.DropDownListFor(model => model.Tyre_Size, new SelectList(@ViewBag.tyresize, "Token_number", "Tyre_size1"),
                                                    "Select Tyre Size", new { @class = "form-control pp", @onchange = "calculate()" })

                    @Html.ValidationMessageFor(model => model.Tyre_Size, "", new { @class = "text-danger" })

                </div>
                <div class="form-group col-md-3 col-lg-3 col-sm-3">
                    @Html.LabelFor(model => model.Supplier_name)
                    @Html.DropDownListFor(model => model.Supplier_token, new SelectList(@ViewBag.dlr, "Token_number", "Name"),
                                                    "Select Supplier token", new { @class = "form-control pp", @onchange = "calculate()" })

                    @Html.ValidationMessageFor(model => model.Supplier_name, "", new { @class = "text-danger" })

                </div>

            </div>
            <div style="padding:3px 3px 3px 3px" class="col-md-12 col-lg-12 col-sm-12">
                <div class="form-group col-md-4 col-lg-4 col-sm-4">
                    @Html.LabelFor(model => model.Purchase_Price)
                    @Html.EditorFor(model => model.Purchase_Price, new { htmlAttributes = new { @class = "form-control nm" } })
                    @Html.ValidationMessageFor(model => model.Purchase_Price, "", new { @class = "text-danger" })


                </div>

                <div class="form-group col-md-4 col-lg-4 col-sm-4">
                    @Html.LabelFor(model => model.SGST)
                    @Html.EditorFor(model => model.SGST, new { htmlAttributes = new { @class = "form-control nm" } })

                    @Html.ValidationMessageFor(model => model.SGST, "", new { @class = "text-danger" })
                </div>
                <div class="form-group col-md-4 col-lg-4 col-sm-4">
                    @Html.LabelFor(model => model.CGST)
                    @Html.EditorFor(model => model.CGST, new { htmlAttributes = new { @class = "form-control nm" } })

                    @Html.ValidationMessageFor(model => model.CGST, "", new { @class = "text-danger" })
                </div>
                <div class="form-group col-md-4 col-lg-4 col-sm-4">
                    @Html.LabelFor(model => model.Pieces)
                    @Html.EditorFor(model => model.Pieces, new { htmlAttributes = new { @class = "form-control nm" } })

                    @Html.ValidationMessageFor(model => model.Pieces, "", new { @class = "text-danger" })
                </div>
                <div class="form-group col-md-4 col-lg-4 col-sm-4">
                    @Html.LabelFor(model => model.Selling_Price)
                    @Html.EditorFor(model => model.Selling_Price, new { htmlAttributes = new { @class = "form-control nm" } })

                    @Html.ValidationMessageFor(model => model.Selling_Price, "", new { @class = "text-danger" })

                </div>
                <div class="form-group col-md-4 col-lg-4 col-sm-4">
                    @Html.LabelFor(model => model.Total)
                    @Html.EditorFor(model => model.Total, new { htmlAttributes = new { @class = "form-control nm" } })

                    @Html.ValidationMessageFor(model => model.Total, "", new { @class = "text-danger" })

                </div>
                <input type="submit" class="form-control" value="Submit" />

            </div>
        }
    </div>
    @*</form>*@
</div>
<script>
$(document).ready( function () {
    $('#myTable').DataTable();
});
</script>

Easy Billing/Easy Billing/Views/ProductsForSale/Delete.cshtml
@model EasyBilling.Models.Products_For_Sale

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Products_For_Sale</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product_Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product_Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HSN_SAC_Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HSN_SAC_Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tax_rate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tax_rate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GL_CODE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GL_CODE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sell_On)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sell_On)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pieces)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pieces)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Weight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Weight)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Unit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Unit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amout_after_tax)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amout_after_tax)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Discount_last_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Discount_last_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Discount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Discount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Single_product_not_combo_multi_)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Single_product_not_combo_multi_)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Marchent_Token_number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Marchent_Token_number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product.Product_Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product.Product_Code)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Easy Billing/Easy Billing/Views/ProductsForSale/ProductDetails.cshtml
@{
    ViewBag.Title = "ProductDetails";
}

<h2>ProductDetails</h2>

Easy Billing/Easy Billing/Views/ProductsForSale/RateUpdate.cshtml
@model IEnumerable<EasyBilling.Models.Products_For_Sale>

@{
    ViewBag.Title = "RateUpdate";
}

<h2>Tyre Rate Update</h2>
<div style="background-color:white;margin:10px 10px 10px 10px">

    <table class="table table-bordered">
        <tr>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Product_name)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Tyre_Size)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Selling_Price)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.CGST)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.SGST)
            </th>

            <th scope="col">
                @Html.DisplayNameFor(model => model.Up_Selling_Price)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Up_CGST)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Up_SGST)
            </th>
        
            <th scope="col">Action</th>
        </tr>
        @{ 
            int count = 0;
        }
        @foreach (var item in Model)
        {
            count++;
            <tr id="tr_@count">

                <td >
                @Html.DisplayFor(modelItem => item.Product_name)
                </td >
                @foreach (var i in @ViewBag.tyresize)
                {
                    if (i.Token_number == item.Tyre_Size)
                    {
                        <td>
                            @i.Tyre_size1
                        </td>
                    }
                    else
                    {
                        <td>
                            -
                        </td>
                    }
                }
                <td>
                    @Html.DisplayFor(modelItem => item.Selling_Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CGST)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SGST)
                </td>
              
                    <td id="upselling">
                        <input type="hidden" id="Token_Number_@count" value="@item.Token_Number"/>
                     
                        <input type="text" id="Up_Selling_Price_@count" name="Up_Selling_Price_@count"/>
                    </td>
                    <td>
                        <input type="text" id="Up_CGST_@count" name="Up_CGST_@count" />
                       
                    </td>
                    <td>
                        <input type="text" id="Up_SGST_@count" name="Up_SGST_@count" />
                    
                    </td>
                    <td>

                        <button type="button" onclick="myFunction(@count)" style="color:white;background-color: #EC5252;border: 1px solid transparent;">Update rate</button>
                    </td>
               
            </tr>

        }

    </table>
</div>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script type="text/javascript">
    function myFunction(val) {
        var Token_number = $('#Token_Number_' + val).val();
        var UpSellingp = $('#Up_Selling_Price_' + val).val();
        var Upcgst = $('#Up_CGST_' + val).val();
        var Upsgst = $('#Up_SGST_' + val).val();
       
        $.ajax({
            type: "POST",
            url: "http://localhost:8087/api/Product/PostRateUpdate",
            cache: false,
            data: JSON.stringify({ Token_number: Token_number, UpSellingp: UpSellingp, Upcgst: Upcgst, Upsgst: Upsgst }),
            contentType: "application/json; charset=utf-8",
            traditional: true,

            success: function (data, textStatus, xhr) {

                alert("Rate updated successfully. Thank you.");
                location.reload();
            },

            error: function (xhr, textStatus, errorThrown) {

                alert('Sorry! something error. Please try again');

            }

        });

    }
</script>